### ISSUE TITLE
Android app crashes when there are ~3,000 transactions

### ISSUE THREAD

**Issue by msbrogli** [HathorNetwork/hathor-wallet-mobile#52]
The app crashes before showing the PIN screen. It just shows a blank screen (see the screenshot below). User tried to restart the cellphone, but the problem remained the same.

Operating System: Android 9
Mobile device: Xiaomi Mi A2 lite 64Gb
RAM memory: 3GB

The user had to delete, reinstall the app, and create a new wallet. To access their funds, the user had to install the app in an iPad (which became really slow when it reached ~5,000 transactions).

![WhatsApp Image 2020-02-26 at 1 41 01 AM](https://user-images.githubusercontent.com/449119/78413676-5c916780-75cd-11ea-8202-96cbc32174fd.jpeg)

**Comment by pedroferreira1** [comment]
Tested with an iPhone 7 that has 2GB of RAM and the wallet opened without a problem (4100 transactions).

I will try to generate a new local wallet with more transactions to continue the tests.

**Comment by pedroferreira1** [comment]
Local tests on iPhone 7:

First test with 6k transactions: the wallet opened without a problem.

Second test with 12k transactions:

- App took 2 minutos to download all the transactions (is was connected to a local test node);
- App took 15 minutos to process all the transactions and open the wallet;
- Everything worked fine after it was opened.

Will try to test with 20k transactions.

**Comment by pedroferreira1** [comment]
Tested with 20k transactions.

- App took 3 minutos to download all the transactions (is was connected to a local test node);
- App took 50 minutos to process all the transactions and open the wallet;
- Everything worked fine after it was opened.

**Comment by pedroferreira1** [comment]
The user that reported the issue was using an older version of the app (v0.8.3) and when tried in the current version (v0.9.1), that has the address history pagination, he didn't have problems loading the data.

However, during the tests one important issue was found.

Tested with 20k transactions on Samsung galaxy S8:

After 6k transactions the app started getting a warning when trying to save data in the storage (see image below).

![image](https://user-images.githubusercontent.com/3298774/79023745-6da32100-7b57-11ea-8b4f-32aceb4a178d.png)

This error happens only on android because of a limitation in the `AsyncStorage` library.

> The iOS AsyncStorage implementation has an unlimited amount of space by default. This is not the case on Android, the default size of AsyncStorage is 6MB. (https://codedaily.io/tutorials/4/Increase-Android-AsyncStorage-Size-in-React-Native)

What is interesting is that the data stored in the `AsyncStorage` should be the persistent data and the history of transactions shouldn't be there. However, in the app storage we were saving the history in both memory and async storage.

The PR https://github.com/HathorNetwork/hathor-wallet-mobile/pull/53 fixes this. So now when loading the 20k transactions wallet there are no errors (it just still takes forever to load).
